/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.clinicalobs.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.restwiz.clinicalobs.Recovery;

/**
 * Service object for domain model class {@link Recovery}.
 */
public interface RecoveryService {

    /**
     * Creates a new Recovery. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Recovery if any.
     *
     * @param recovery Details of the Recovery to be created; value cannot be null.
     * @return The newly created Recovery.
     */
    Recovery create(@Valid Recovery recovery);


	/**
     * Returns Recovery by given id if exists.
     *
     * @param recoveryIdInstance The id of the Recovery to get; value cannot be null.
     * @return Recovery associated with the given recoveryIdInstance.
	 * @throws EntityNotFoundException If no Recovery is found.
     */
    Recovery getById(Integer recoveryIdInstance);

    /**
     * Find and return the Recovery by given id if exists, returns null otherwise.
     *
     * @param recoveryIdInstance The id of the Recovery to get; value cannot be null.
     * @return Recovery associated with the given recoveryIdInstance.
     */
    Recovery findById(Integer recoveryIdInstance);

	/**
     * Find and return the list of Recoveries by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param recoveryIdInstances The id's of the Recovery to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Recoveries associated with the given recoveryIdInstances.
     */
    List<Recovery> findByMultipleIds(List<Integer> recoveryIdInstances, boolean orderedReturn);


    /**
     * Updates the details of an existing Recovery. It replaces all fields of the existing Recovery with the given recovery.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Recovery if any.
     *
     * @param recovery The details of the Recovery to be updated; value cannot be null.
     * @return The updated Recovery.
     * @throws EntityNotFoundException if no Recovery is found with given input.
     */
    Recovery update(@Valid Recovery recovery);

    /**
     * Deletes an existing Recovery with the given id.
     *
     * @param recoveryIdInstance The id of the Recovery to be deleted; value cannot be null.
     * @return The deleted Recovery.
     * @throws EntityNotFoundException if no Recovery found with the given id.
     */
    Recovery delete(Integer recoveryIdInstance);

    /**
     * Deletes an existing Recovery with the given object.
     *
     * @param recovery The instance of the Recovery to be deleted; value cannot be null.
     */
    void delete(Recovery recovery);

    /**
     * Find all Recoveries matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Recoveries.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Recovery> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Recoveries matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Recoveries.
     *
     * @see Pageable
     * @see Page
     */
    Page<Recovery> findAll(String query, Pageable pageable);

    /**
     * Exports all Recoveries matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Recoveries matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Recoveries in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Recovery.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}