/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryGetAllEmailByPatientNoResponse implements Serializable {


    @ColumnAlias("report_dte")
    private LocalDateTime reportDte;

    @ColumnAlias("report_tme")
    private String reportTme;

    @ColumnAlias("srvcno")
    private Integer srvcno;

    @ColumnAlias("status")
    private String status;

    @ColumnAlias("report_txt")
    private String reportTxt;

    @ColumnAlias("mobileno")
    private String mobileno;

    @ColumnAlias("messageid")
    private String messageid;

    @ColumnAlias("replymsgid")
    private String replymsgid;

    @ColumnAlias("sms_inoout")
    private String smsInoout;

    public LocalDateTime getReportDte() {
        return this.reportDte;
    }

    public void setReportDte(LocalDateTime reportDte) {
        this.reportDte = reportDte;
    }

    public String getReportTme() {
        return this.reportTme;
    }

    public void setReportTme(String reportTme) {
        this.reportTme = reportTme;
    }

    public Integer getSrvcno() {
        return this.srvcno;
    }

    public void setSrvcno(Integer srvcno) {
        this.srvcno = srvcno;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReportTxt() {
        return this.reportTxt;
    }

    public void setReportTxt(String reportTxt) {
        this.reportTxt = reportTxt;
    }

    public String getMobileno() {
        return this.mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    public String getMessageid() {
        return this.messageid;
    }

    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    public String getReplymsgid() {
        return this.replymsgid;
    }

    public void setReplymsgid(String replymsgid) {
        this.replymsgid = replymsgid;
    }

    public String getSmsInoout() {
        return this.smsInoout;
    }

    public void setSmsInoout(String smsInoout) {
        this.smsInoout = smsInoout;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryGetAllEmailByPatientNoResponse)) return false;
        final QryGetAllEmailByPatientNoResponse qryGetAllEmailByPatientNoResponse = (QryGetAllEmailByPatientNoResponse) o;
        return Objects.equals(getReportDte(), qryGetAllEmailByPatientNoResponse.getReportDte()) &&
                Objects.equals(getReportTme(), qryGetAllEmailByPatientNoResponse.getReportTme()) &&
                Objects.equals(getSrvcno(), qryGetAllEmailByPatientNoResponse.getSrvcno()) &&
                Objects.equals(getStatus(), qryGetAllEmailByPatientNoResponse.getStatus()) &&
                Objects.equals(getReportTxt(), qryGetAllEmailByPatientNoResponse.getReportTxt()) &&
                Objects.equals(getMobileno(), qryGetAllEmailByPatientNoResponse.getMobileno()) &&
                Objects.equals(getMessageid(), qryGetAllEmailByPatientNoResponse.getMessageid()) &&
                Objects.equals(getReplymsgid(), qryGetAllEmailByPatientNoResponse.getReplymsgid()) &&
                Objects.equals(getSmsInoout(), qryGetAllEmailByPatientNoResponse.getSmsInoout());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getReportDte(),
                getReportTme(),
                getSrvcno(),
                getStatus(),
                getReportTxt(),
                getMobileno(),
                getMessageid(),
                getReplymsgid(),
                getSmsInoout());
    }
}