/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryGetAllAppointmentByPatientNoResponse implements Serializable {


    @ColumnAlias("b_date")
    private LocalDateTime bdate;

    @ColumnAlias("b_time")
    private String btime;

    @ColumnAlias("e_time")
    private String etime;

    @ColumnAlias("cal_desc")
    private String calDesc;

    @ColumnAlias("apmadeon")
    private LocalDateTime apmadeon;

    @ColumnAlias("apmadeat")
    private String apmadeat;

    @ColumnAlias("opnotes")
    private String opnotes;

    @ColumnAlias("title")
    private String title;

    @ColumnAlias("given")
    private String given;

    @ColumnAlias("surname")
    private String surname;

    @ColumnAlias("blueprntcd")
    private String blueprntcd;

    @ColumnAlias("longname")
    private String longname;

    public LocalDateTime getBdate() {
        return this.bdate;
    }

    public void setBdate(LocalDateTime bdate) {
        this.bdate = bdate;
    }

    public String getBtime() {
        return this.btime;
    }

    public void setBtime(String btime) {
        this.btime = btime;
    }

    public String getEtime() {
        return this.etime;
    }

    public void setEtime(String etime) {
        this.etime = etime;
    }

    public String getCalDesc() {
        return this.calDesc;
    }

    public void setCalDesc(String calDesc) {
        this.calDesc = calDesc;
    }

    public LocalDateTime getApmadeon() {
        return this.apmadeon;
    }

    public void setApmadeon(LocalDateTime apmadeon) {
        this.apmadeon = apmadeon;
    }

    public String getApmadeat() {
        return this.apmadeat;
    }

    public void setApmadeat(String apmadeat) {
        this.apmadeat = apmadeat;
    }

    public String getOpnotes() {
        return this.opnotes;
    }

    public void setOpnotes(String opnotes) {
        this.opnotes = opnotes;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGiven() {
        return this.given;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getBlueprntcd() {
        return this.blueprntcd;
    }

    public void setBlueprntcd(String blueprntcd) {
        this.blueprntcd = blueprntcd;
    }

    public String getLongname() {
        return this.longname;
    }

    public void setLongname(String longname) {
        this.longname = longname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryGetAllAppointmentByPatientNoResponse)) return false;
        final QryGetAllAppointmentByPatientNoResponse qryGetAllAppointmentByPatientNoResponse = (QryGetAllAppointmentByPatientNoResponse) o;
        return Objects.equals(getBdate(), qryGetAllAppointmentByPatientNoResponse.getBdate()) &&
                Objects.equals(getBtime(), qryGetAllAppointmentByPatientNoResponse.getBtime()) &&
                Objects.equals(getEtime(), qryGetAllAppointmentByPatientNoResponse.getEtime()) &&
                Objects.equals(getCalDesc(), qryGetAllAppointmentByPatientNoResponse.getCalDesc()) &&
                Objects.equals(getApmadeon(), qryGetAllAppointmentByPatientNoResponse.getApmadeon()) &&
                Objects.equals(getApmadeat(), qryGetAllAppointmentByPatientNoResponse.getApmadeat()) &&
                Objects.equals(getOpnotes(), qryGetAllAppointmentByPatientNoResponse.getOpnotes()) &&
                Objects.equals(getTitle(), qryGetAllAppointmentByPatientNoResponse.getTitle()) &&
                Objects.equals(getGiven(), qryGetAllAppointmentByPatientNoResponse.getGiven()) &&
                Objects.equals(getSurname(), qryGetAllAppointmentByPatientNoResponse.getSurname()) &&
                Objects.equals(getBlueprntcd(), qryGetAllAppointmentByPatientNoResponse.getBlueprntcd()) &&
                Objects.equals(getLongname(), qryGetAllAppointmentByPatientNoResponse.getLongname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBdate(),
                getBtime(),
                getEtime(),
                getCalDesc(),
                getApmadeon(),
                getApmadeat(),
                getOpnotes(),
                getTitle(),
                getGiven(),
                getSurname(),
                getBlueprntcd(),
                getLongname());
    }
}