/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryGetAppointmentByPatientNoResponse implements Serializable {


    @ColumnAlias("b_date")
    private LocalDateTime bdate;

    @ColumnAlias("b_time")
    private String btime;

    @ColumnAlias("e_time")
    private String etime;

    @ColumnAlias("cal_desc")
    private String calDesc;

    @ColumnAlias("apmadeon")
    private LocalDateTime apmadeon;

    @ColumnAlias("apmadeat")
    private String apmadeat;

    public LocalDateTime getBdate() {
        return this.bdate;
    }

    public void setBdate(LocalDateTime bdate) {
        this.bdate = bdate;
    }

    public String getBtime() {
        return this.btime;
    }

    public void setBtime(String btime) {
        this.btime = btime;
    }

    public String getEtime() {
        return this.etime;
    }

    public void setEtime(String etime) {
        this.etime = etime;
    }

    public String getCalDesc() {
        return this.calDesc;
    }

    public void setCalDesc(String calDesc) {
        this.calDesc = calDesc;
    }

    public LocalDateTime getApmadeon() {
        return this.apmadeon;
    }

    public void setApmadeon(LocalDateTime apmadeon) {
        this.apmadeon = apmadeon;
    }

    public String getApmadeat() {
        return this.apmadeat;
    }

    public void setApmadeat(String apmadeat) {
        this.apmadeat = apmadeat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryGetAppointmentByPatientNoResponse)) return false;
        final QryGetAppointmentByPatientNoResponse qryGetAppointmentByPatientNoResponse = (QryGetAppointmentByPatientNoResponse) o;
        return Objects.equals(getBdate(), qryGetAppointmentByPatientNoResponse.getBdate()) &&
                Objects.equals(getBtime(), qryGetAppointmentByPatientNoResponse.getBtime()) &&
                Objects.equals(getEtime(), qryGetAppointmentByPatientNoResponse.getEtime()) &&
                Objects.equals(getCalDesc(), qryGetAppointmentByPatientNoResponse.getCalDesc()) &&
                Objects.equals(getApmadeon(), qryGetAppointmentByPatientNoResponse.getApmadeon()) &&
                Objects.equals(getApmadeat(), qryGetAppointmentByPatientNoResponse.getApmadeat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBdate(),
                getBtime(),
                getEtime(),
                getCalDesc(),
                getApmadeon(),
                getApmadeat());
    }
}