/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryGetRecalsByPatientNoResponse implements Serializable {


    @ColumnAlias("details")
    private String details;

    @ColumnAlias("treatmnt")
    private String treatmnt;

    @ColumnAlias("tests")
    private String tests;

    @ColumnAlias("date")
    private LocalDateTime date;

    @ColumnAlias("title")
    private String title;

    @ColumnAlias("given")
    private String given;

    @ColumnAlias("surname")
    private String surname;

    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getTreatmnt() {
        return this.treatmnt;
    }

    public void setTreatmnt(String treatmnt) {
        this.treatmnt = treatmnt;
    }

    public String getTests() {
        return this.tests;
    }

    public void setTests(String tests) {
        this.tests = tests;
    }

    public LocalDateTime getDate() {
        return this.date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGiven() {
        return this.given;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryGetRecalsByPatientNoResponse)) return false;
        final QryGetRecalsByPatientNoResponse qryGetRecalsByPatientNoResponse = (QryGetRecalsByPatientNoResponse) o;
        return Objects.equals(getDetails(), qryGetRecalsByPatientNoResponse.getDetails()) &&
                Objects.equals(getTreatmnt(), qryGetRecalsByPatientNoResponse.getTreatmnt()) &&
                Objects.equals(getTests(), qryGetRecalsByPatientNoResponse.getTests()) &&
                Objects.equals(getDate(), qryGetRecalsByPatientNoResponse.getDate()) &&
                Objects.equals(getTitle(), qryGetRecalsByPatientNoResponse.getTitle()) &&
                Objects.equals(getGiven(), qryGetRecalsByPatientNoResponse.getGiven()) &&
                Objects.equals(getSurname(), qryGetRecalsByPatientNoResponse.getSurname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDetails(),
                getTreatmnt(),
                getTests(),
                getDate(),
                getTitle(),
                getGiven(),
                getSurname());
    }
}