/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class QryUpdateAccountNoRequest implements Serializable {


    @JsonProperty("t_accountNo")
    @NotNull
    private String taccountNo;

    @JsonProperty("t_patientNo")
    @NotNull
    private String tpatientNo;

    public String getTaccountNo() {
        return this.taccountNo;
    }

    public void setTaccountNo(String taccountNo) {
        this.taccountNo = taccountNo;
    }

    public String getTpatientNo() {
        return this.tpatientNo;
    }

    public void setTpatientNo(String tpatientNo) {
        this.tpatientNo = tpatientNo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryUpdateAccountNoRequest)) return false;
        final QryUpdateAccountNoRequest qryUpdateAccountNoRequest = (QryUpdateAccountNoRequest) o;
        return Objects.equals(getTaccountNo(), qryUpdateAccountNoRequest.getTaccountNo()) &&
                Objects.equals(getTpatientNo(), qryUpdateAccountNoRequest.getTpatientNo());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTaccountNo(),
                getTpatientNo());
    }
}