/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class QryUpdateSmsreadStatusRequest implements Serializable {


    @JsonProperty("messageid")
    @NotNull
    private String messageid;

    public String getMessageid() {
        return this.messageid;
    }

    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryUpdateSmsreadStatusRequest)) return false;
        final QryUpdateSmsreadStatusRequest qryUpdateSmsreadStatusRequest = (QryUpdateSmsreadStatusRequest) o;
        return Objects.equals(getMessageid(), qryUpdateSmsreadStatusRequest.getMessageid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMessageid());
    }
}