/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.clinicalobs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clinicalalerts generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`clinicalalerts`")
public class Clinicalalerts implements Serializable {

    private Integer alertId;
    private String alertcode;
    private String alertdescription;
    private String alerttext;
    private Integer sortorder;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`alert_id`", nullable = false, scale = 0, precision = 10)
    public Integer getAlertId() {
        return this.alertId;
    }

    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }

    @Column(name = "`alertcode`", nullable = false, length = 50)
    public String getAlertcode() {
        return this.alertcode;
    }

    public void setAlertcode(String alertcode) {
        this.alertcode = alertcode;
    }

    @Column(name = "`alertdescription`", nullable = true, length = 250)
    public String getAlertdescription() {
        return this.alertdescription;
    }

    public void setAlertdescription(String alertdescription) {
        this.alertdescription = alertdescription;
    }

    @Column(name = "`alerttext`", nullable = true, length = 65535)
    public String getAlerttext() {
        return this.alerttext;
    }

    public void setAlerttext(String alerttext) {
        this.alerttext = alerttext;
    }

    @Column(name = "`sortorder`", nullable = true, scale = 0, precision = 10)
    public Integer getSortorder() {
        return this.sortorder;
    }

    public void setSortorder(Integer sortorder) {
        this.sortorder = sortorder;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Clinicalalerts)) return false;
        final Clinicalalerts clinicalalerts = (Clinicalalerts) o;
        return Objects.equals(getAlertId(), clinicalalerts.getAlertId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAlertId());
    }
}