/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.clinicalobs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IgnoredAllergy generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`IgnoredAllergy`")
public class IgnoredAllergy implements Serializable {

    private Integer allergyId;
    private String allergyName;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`allergyId`", nullable = false, scale = 0, precision = 10)
    public Integer getAllergyId() {
        return this.allergyId;
    }

    public void setAllergyId(Integer allergyId) {
        this.allergyId = allergyId;
    }

    @Column(name = "`allergyName`", nullable = true, length = 255)
    public String getAllergyName() {
        return this.allergyName;
    }

    public void setAllergyName(String allergyName) {
        this.allergyName = allergyName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof IgnoredAllergy)) return false;
        final IgnoredAllergy ignoredAllergy = (IgnoredAllergy) o;
        return Objects.equals(getAllergyId(), ignoredAllergy.getAllergyId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAllergyId());
    }
}