/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.clinicalobs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * PtAllergy generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ptAllergy`")
public class PtAllergy implements Serializable {

    private Integer idno;
    private String allergyReaction;
    private Integer fkAllergy;
    private Integer obsptid;
    private Obspatients obspatients;
    private Allergies allergiesByObsptid;
    private Allergies allergiesByFkAllergy;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`idno`", nullable = false, scale = 0, precision = 10)
    public Integer getIdno() {
        return this.idno;
    }

    public void setIdno(Integer idno) {
        this.idno = idno;
    }

    @Column(name = "`allergyReaction`", nullable = true, length = 255)
    public String getAllergyReaction() {
        return this.allergyReaction;
    }

    public void setAllergyReaction(String allergyReaction) {
        this.allergyReaction = allergyReaction;
    }

    @Column(name = "`fkAllergy`", nullable = true, scale = 0, precision = 10)
    public Integer getFkAllergy() {
        return this.fkAllergy;
    }

    public void setFkAllergy(Integer fkAllergy) {
        this.fkAllergy = fkAllergy;
    }

    @Column(name = "`obsptid`", nullable = true, scale = 0, precision = 10)
    public Integer getObsptid() {
        return this.obsptid;
    }

    public void setObsptid(Integer obsptid) {
        this.obsptid = obsptid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`obsptid`", referencedColumnName = "`obsptid`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_ptAllergy_TO_obspatiefLFF5`"))
    @Fetch(FetchMode.JOIN)
    public Obspatients getObspatients() {
        return this.obspatients;
    }

    public void setObspatients(Obspatients obspatients) {
        if(obspatients != null) {
            this.obsptid = obspatients.getObsptid();
        }

        this.obspatients = obspatients;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`obsptid`", referencedColumnName = "`allergy_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_ptAllergy_TO_allergiec8eBq`"))
    @Fetch(FetchMode.JOIN)
    public Allergies getAllergiesByObsptid() {
        return this.allergiesByObsptid;
    }

    public void setAllergiesByObsptid(Allergies allergiesByObsptid) {
        if(allergiesByObsptid != null) {
            this.obsptid = allergiesByObsptid.getAllergyId();
        }

        this.allergiesByObsptid = allergiesByObsptid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`fkAllergy`", referencedColumnName = "`allergy_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_ptAllergy_TO_allergie9Uq4F`"))
    @Fetch(FetchMode.JOIN)
    public Allergies getAllergiesByFkAllergy() {
        return this.allergiesByFkAllergy;
    }

    public void setAllergiesByFkAllergy(Allergies allergiesByFkAllergy) {
        if(allergiesByFkAllergy != null) {
            this.fkAllergy = allergiesByFkAllergy.getAllergyId();
        }

        this.allergiesByFkAllergy = allergiesByFkAllergy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PtAllergy)) return false;
        final PtAllergy ptAllergy = (PtAllergy) o;
        return Objects.equals(getIdno(), ptAllergy.getIdno());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdno());
    }
}