/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.clinicalobs;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Surgchecklist generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`surgchecklist`")
public class Surgchecklist implements Serializable {

    private Integer checklistId;
    private String userId2;
    private String userId3;
    private String userId5;
    private String userId6;
    private String userId2pin;
    private String userId3pin;
    private String userId5pin;
    private String userId6pin;
    private LocalDateTime userId2date;
    private LocalDateTime userId3date;
    private LocalDateTime userId5date;
    private LocalDateTime userId6date;
    private String teamIntroduction;
    private String surgeonAnaConfirm;
    private String surgeonBrief;
    private String nursingReview;
    private String nurseComments;
    private String bloodLossRisk;
    private String adequateIntrav;
    private String groupScreen;
    private String anaesTeam;
    private String antibiotic;
    private String thrombo;
    private String nurseConfirm;
    private String specimens;
    private String postOpPath;
    private String postOpDest;
    private String keyPostOp;
    private String ebldiscussed;
    private String procPerformed;
    private Boolean incomColonoscopy;
    private Integer obsptid;
    private Boolean alcoholicClorhexidine;
    private Boolean alcoholicWipe;
    private Boolean aqueousChlorhexidine;
    private Boolean aqueousClorhexidine;
    private Boolean bairHugg;
    private Boolean bipolar;
    private Boolean bp;
    private Boolean bss;
    private Boolean cephazolinIntracameral;
    private Boolean cetrimide;
    private Boolean chloromycetin;
    private Boolean ciloxanDrops;
    private Boolean cocaineHcl;
    private Boolean compressionKnee;
    private Boolean compressionLeft;
    private Boolean compressionRight;
    private Boolean compressionThigh;
    private Boolean denturesFull;
    private Boolean denturesLeftInsitu;
    private Boolean denturesLower;
    private Boolean denturesNa;
    private Boolean denturesPartial;
    private Boolean denturesRemoved;
    private Boolean denturesUpper;
    private String diathermyAppliedBy;
    private String diathermyRemovedBy;
    private Boolean drugAdded;
    private Boolean duovisc;
    private Boolean ecg;
    private Boolean elbowGels;
    private Boolean emboard;
    private Boolean fluidWarmer;
    private Boolean headRing;
    private Boolean heelGels;
    private Boolean hydrogenPeroxide3;
    private Boolean hydrogenPeroxide6;
    private Boolean infiltrationOther;
    private String infiltrationOtherDesc;
    private Boolean infiltrationOxymetazaline;
    private Boolean intact;
    private Boolean irrigationSolutionOther;
    private String irrigationSolutionOtherDesc;
    private Boolean jboards;
    private Boolean kenacomb;
    private Boolean lateralLeft;
    private Boolean lateralRight;
    private Boolean lignocaine1;
    private Boolean lithotomiPoles;
    private Boolean lithotomiStirrups;
    private Boolean marcainAdrenaline;
    private Boolean medicationAdrenaline;
    private Boolean medicationsOxymetazaline;
    private Boolean monitoringInAntNone;
    private Boolean monopolar;
    private Boolean naropin1;
    private Boolean naropin75;
    private Boolean normalSalineIrrigation;
    private Boolean normalSalineIv;
    private Boolean platesite;
    private Boolean plusOximetry;
    private Boolean positioningAidsOther;
    private Boolean prepSolutionOther;
    private Boolean prone;
    private Boolean providoeIodine10;
    private Boolean providoeIodine5;
    private Boolean providoneIodine;
    private Boolean provisc;
    private Boolean ptPositionOther;
    private Boolean signinForTimeoutComplete;
    private String sitesUsed;
    private Boolean skinIntegrityOther;
    private String skinIntegrityOtherDesc;
    private Boolean skinPrepOther;
    private String skinPrepOtherDisc;
    private Boolean sodiumBicarbonate;
    private Boolean stockingKnee;
    private Boolean stockingLeft;
    private Boolean stockingRight;
    private Boolean stockingThigh;
    private Boolean supine;
    private Boolean temperature;
    private Boolean tisseel;
    private String totalEnvelops;
    private Boolean trenderlengberg;
    private Boolean velcroStrap;
    private Boolean warmBlanket;
    private Boolean warmingNone;
    private Boolean waterforIrrigation;
    private Boolean wedge;
    private Boolean xrayPresent;
    private Boolean xylocaine2;
    private Boolean xylocaineAdrenaline1;
    private Boolean xylocaineAdrenaline2;
    private Boolean marcain5;
    private String skinIntergrityImageText;
    private String createdBy;
    private Timestamp createdDate;
    private String lastUpdateBy;
    private Timestamp lastUpdateDate;
    private Obspatients obspatients;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`Checklist_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getChecklistId() {
        return this.checklistId;
    }

    public void setChecklistId(Integer checklistId) {
        this.checklistId = checklistId;
    }

    @Column(name = "`UserID2`", nullable = true, length = 10)
    public String getUserId2() {
        return this.userId2;
    }

    public void setUserId2(String userId2) {
        this.userId2 = userId2;
    }

    @Column(name = "`UserID3`", nullable = true, length = 10)
    public String getUserId3() {
        return this.userId3;
    }

    public void setUserId3(String userId3) {
        this.userId3 = userId3;
    }

    @Column(name = "`UserID5`", nullable = true, length = 10)
    public String getUserId5() {
        return this.userId5;
    }

    public void setUserId5(String userId5) {
        this.userId5 = userId5;
    }

    @Column(name = "`UserID6`", nullable = true, length = 10)
    public String getUserId6() {
        return this.userId6;
    }

    public void setUserId6(String userId6) {
        this.userId6 = userId6;
    }

    @Column(name = "`UserID2PIN`", nullable = true, length = 10)
    public String getUserId2pin() {
        return this.userId2pin;
    }

    public void setUserId2pin(String userId2pin) {
        this.userId2pin = userId2pin;
    }

    @Column(name = "`UserID3PIN`", nullable = true, length = 10)
    public String getUserId3pin() {
        return this.userId3pin;
    }

    public void setUserId3pin(String userId3pin) {
        this.userId3pin = userId3pin;
    }

    @Column(name = "`UserID5PIN`", nullable = true, length = 10)
    public String getUserId5pin() {
        return this.userId5pin;
    }

    public void setUserId5pin(String userId5pin) {
        this.userId5pin = userId5pin;
    }

    @Column(name = "`UserID6PIN`", nullable = true, length = 10)
    public String getUserId6pin() {
        return this.userId6pin;
    }

    public void setUserId6pin(String userId6pin) {
        this.userId6pin = userId6pin;
    }

    @Column(name = "`UserID2Date`", nullable = true)
    public LocalDateTime getUserId2date() {
        return this.userId2date;
    }

    public void setUserId2date(LocalDateTime userId2date) {
        this.userId2date = userId2date;
    }

    @Column(name = "`UserID3Date`", nullable = true)
    public LocalDateTime getUserId3date() {
        return this.userId3date;
    }

    public void setUserId3date(LocalDateTime userId3date) {
        this.userId3date = userId3date;
    }

    @Column(name = "`UserID5Date`", nullable = true)
    public LocalDateTime getUserId5date() {
        return this.userId5date;
    }

    public void setUserId5date(LocalDateTime userId5date) {
        this.userId5date = userId5date;
    }

    @Column(name = "`UserID6Date`", nullable = true)
    public LocalDateTime getUserId6date() {
        return this.userId6date;
    }

    public void setUserId6date(LocalDateTime userId6date) {
        this.userId6date = userId6date;
    }

    @Column(name = "`TeamIntroduction`", nullable = true, length = 5)
    public String getTeamIntroduction() {
        return this.teamIntroduction;
    }

    public void setTeamIntroduction(String teamIntroduction) {
        this.teamIntroduction = teamIntroduction;
    }

    @Column(name = "`SurgeonAnaConfirm`", nullable = true, length = 5)
    public String getSurgeonAnaConfirm() {
        return this.surgeonAnaConfirm;
    }

    public void setSurgeonAnaConfirm(String surgeonAnaConfirm) {
        this.surgeonAnaConfirm = surgeonAnaConfirm;
    }

    @Column(name = "`SurgeonBrief`", nullable = true, length = 5)
    public String getSurgeonBrief() {
        return this.surgeonBrief;
    }

    public void setSurgeonBrief(String surgeonBrief) {
        this.surgeonBrief = surgeonBrief;
    }

    @Column(name = "`NursingReview`", nullable = true, length = 5)
    public String getNursingReview() {
        return this.nursingReview;
    }

    public void setNursingReview(String nursingReview) {
        this.nursingReview = nursingReview;
    }

    @Column(name = "`NurseComments`", nullable = true, length = 255)
    public String getNurseComments() {
        return this.nurseComments;
    }

    public void setNurseComments(String nurseComments) {
        this.nurseComments = nurseComments;
    }

    @Column(name = "`BloodLossRisk`", nullable = true, length = 5)
    public String getBloodLossRisk() {
        return this.bloodLossRisk;
    }

    public void setBloodLossRisk(String bloodLossRisk) {
        this.bloodLossRisk = bloodLossRisk;
    }

    @Column(name = "`AdequateIntrav`", nullable = true, length = 5)
    public String getAdequateIntrav() {
        return this.adequateIntrav;
    }

    public void setAdequateIntrav(String adequateIntrav) {
        this.adequateIntrav = adequateIntrav;
    }

    @Column(name = "`GroupScreen`", nullable = true, length = 5)
    public String getGroupScreen() {
        return this.groupScreen;
    }

    public void setGroupScreen(String groupScreen) {
        this.groupScreen = groupScreen;
    }

    @Column(name = "`AnaesTeam`", nullable = true, length = 5)
    public String getAnaesTeam() {
        return this.anaesTeam;
    }

    public void setAnaesTeam(String anaesTeam) {
        this.anaesTeam = anaesTeam;
    }

    @Column(name = "`Antibiotic`", nullable = true, length = 5)
    public String getAntibiotic() {
        return this.antibiotic;
    }

    public void setAntibiotic(String antibiotic) {
        this.antibiotic = antibiotic;
    }

    @Column(name = "`Thrombo`", nullable = true, length = 75)
    public String getThrombo() {
        return this.thrombo;
    }

    public void setThrombo(String thrombo) {
        this.thrombo = thrombo;
    }

    @Column(name = "`NurseConfirm`", nullable = true, length = 5)
    public String getNurseConfirm() {
        return this.nurseConfirm;
    }

    public void setNurseConfirm(String nurseConfirm) {
        this.nurseConfirm = nurseConfirm;
    }

    @Column(name = "`Specimens`", nullable = true, length = 5)
    public String getSpecimens() {
        return this.specimens;
    }

    public void setSpecimens(String specimens) {
        this.specimens = specimens;
    }

    @Column(name = "`PostOpPath`", nullable = true, length = 30)
    public String getPostOpPath() {
        return this.postOpPath;
    }

    public void setPostOpPath(String postOpPath) {
        this.postOpPath = postOpPath;
    }

    @Column(name = "`PostOpDest`", nullable = true, length = 5)
    public String getPostOpDest() {
        return this.postOpDest;
    }

    public void setPostOpDest(String postOpDest) {
        this.postOpDest = postOpDest;
    }

    @Column(name = "`KeyPostOp`", nullable = true, length = 5)
    public String getKeyPostOp() {
        return this.keyPostOp;
    }

    public void setKeyPostOp(String keyPostOp) {
        this.keyPostOp = keyPostOp;
    }

    @Column(name = "`EBLDiscussed`", nullable = true, length = 5)
    public String getEbldiscussed() {
        return this.ebldiscussed;
    }

    public void setEbldiscussed(String ebldiscussed) {
        this.ebldiscussed = ebldiscussed;
    }

    @Column(name = "`ProcPerformed`", nullable = true, length = 5)
    public String getProcPerformed() {
        return this.procPerformed;
    }

    public void setProcPerformed(String procPerformed) {
        this.procPerformed = procPerformed;
    }

    @Column(name = "`IncomColonoscopy`", nullable = true)
    public Boolean getIncomColonoscopy() {
        return this.incomColonoscopy;
    }

    public void setIncomColonoscopy(Boolean incomColonoscopy) {
        this.incomColonoscopy = incomColonoscopy;
    }

    @Column(name = "`obsptid`", nullable = true, scale = 0, precision = 10)
    public Integer getObsptid() {
        return this.obsptid;
    }

    public void setObsptid(Integer obsptid) {
        this.obsptid = obsptid;
    }

    @Column(name = "`AlcoholicClorhexidine`", nullable = true)
    public Boolean getAlcoholicClorhexidine() {
        return this.alcoholicClorhexidine;
    }

    public void setAlcoholicClorhexidine(Boolean alcoholicClorhexidine) {
        this.alcoholicClorhexidine = alcoholicClorhexidine;
    }

    @Column(name = "`AlcoholicWipe`", nullable = true)
    public Boolean getAlcoholicWipe() {
        return this.alcoholicWipe;
    }

    public void setAlcoholicWipe(Boolean alcoholicWipe) {
        this.alcoholicWipe = alcoholicWipe;
    }

    @Column(name = "`AqueousChlorhexidine`", nullable = true)
    public Boolean getAqueousChlorhexidine() {
        return this.aqueousChlorhexidine;
    }

    public void setAqueousChlorhexidine(Boolean aqueousChlorhexidine) {
        this.aqueousChlorhexidine = aqueousChlorhexidine;
    }

    @Column(name = "`AqueousClorhexidine`", nullable = true)
    public Boolean getAqueousClorhexidine() {
        return this.aqueousClorhexidine;
    }

    public void setAqueousClorhexidine(Boolean aqueousClorhexidine) {
        this.aqueousClorhexidine = aqueousClorhexidine;
    }

    @Column(name = "`BairHugg`", nullable = true)
    public Boolean getBairHugg() {
        return this.bairHugg;
    }

    public void setBairHugg(Boolean bairHugg) {
        this.bairHugg = bairHugg;
    }

    @Column(name = "`Bipolar`", nullable = true)
    public Boolean getBipolar() {
        return this.bipolar;
    }

    public void setBipolar(Boolean bipolar) {
        this.bipolar = bipolar;
    }

    @Column(name = "`BP`", nullable = true)
    public Boolean getBp() {
        return this.bp;
    }

    public void setBp(Boolean bp) {
        this.bp = bp;
    }

    @Column(name = "`BSS`", nullable = true)
    public Boolean getBss() {
        return this.bss;
    }

    public void setBss(Boolean bss) {
        this.bss = bss;
    }

    @Column(name = "`CephazolinIntracameral`", nullable = true)
    public Boolean getCephazolinIntracameral() {
        return this.cephazolinIntracameral;
    }

    public void setCephazolinIntracameral(Boolean cephazolinIntracameral) {
        this.cephazolinIntracameral = cephazolinIntracameral;
    }

    @Column(name = "`Cetrimide`", nullable = true)
    public Boolean getCetrimide() {
        return this.cetrimide;
    }

    public void setCetrimide(Boolean cetrimide) {
        this.cetrimide = cetrimide;
    }

    @Column(name = "`Chloromycetin`", nullable = true)
    public Boolean getChloromycetin() {
        return this.chloromycetin;
    }

    public void setChloromycetin(Boolean chloromycetin) {
        this.chloromycetin = chloromycetin;
    }

    @Column(name = "`CiloxanDrops`", nullable = true)
    public Boolean getCiloxanDrops() {
        return this.ciloxanDrops;
    }

    public void setCiloxanDrops(Boolean ciloxanDrops) {
        this.ciloxanDrops = ciloxanDrops;
    }

    @Column(name = "`CocaineHCL`", nullable = true)
    public Boolean getCocaineHcl() {
        return this.cocaineHcl;
    }

    public void setCocaineHcl(Boolean cocaineHcl) {
        this.cocaineHcl = cocaineHcl;
    }

    @Column(name = "`CompressionKnee`", nullable = true)
    public Boolean getCompressionKnee() {
        return this.compressionKnee;
    }

    public void setCompressionKnee(Boolean compressionKnee) {
        this.compressionKnee = compressionKnee;
    }

    @Column(name = "`CompressionLeft`", nullable = true)
    public Boolean getCompressionLeft() {
        return this.compressionLeft;
    }

    public void setCompressionLeft(Boolean compressionLeft) {
        this.compressionLeft = compressionLeft;
    }

    @Column(name = "`CompressionRight`", nullable = true)
    public Boolean getCompressionRight() {
        return this.compressionRight;
    }

    public void setCompressionRight(Boolean compressionRight) {
        this.compressionRight = compressionRight;
    }

    @Column(name = "`CompressionThigh`", nullable = true)
    public Boolean getCompressionThigh() {
        return this.compressionThigh;
    }

    public void setCompressionThigh(Boolean compressionThigh) {
        this.compressionThigh = compressionThigh;
    }

    @Column(name = "`DenturesFull`", nullable = true)
    public Boolean getDenturesFull() {
        return this.denturesFull;
    }

    public void setDenturesFull(Boolean denturesFull) {
        this.denturesFull = denturesFull;
    }

    @Column(name = "`DenturesLeftInsitu`", nullable = true)
    public Boolean getDenturesLeftInsitu() {
        return this.denturesLeftInsitu;
    }

    public void setDenturesLeftInsitu(Boolean denturesLeftInsitu) {
        this.denturesLeftInsitu = denturesLeftInsitu;
    }

    @Column(name = "`DenturesLower`", nullable = true)
    public Boolean getDenturesLower() {
        return this.denturesLower;
    }

    public void setDenturesLower(Boolean denturesLower) {
        this.denturesLower = denturesLower;
    }

    @Column(name = "`DenturesNA`", nullable = true)
    public Boolean getDenturesNa() {
        return this.denturesNa;
    }

    public void setDenturesNa(Boolean denturesNa) {
        this.denturesNa = denturesNa;
    }

    @Column(name = "`DenturesPartial`", nullable = true)
    public Boolean getDenturesPartial() {
        return this.denturesPartial;
    }

    public void setDenturesPartial(Boolean denturesPartial) {
        this.denturesPartial = denturesPartial;
    }

    @Column(name = "`DenturesRemoved`", nullable = true)
    public Boolean getDenturesRemoved() {
        return this.denturesRemoved;
    }

    public void setDenturesRemoved(Boolean denturesRemoved) {
        this.denturesRemoved = denturesRemoved;
    }

    @Column(name = "`DenturesUpper`", nullable = true)
    public Boolean getDenturesUpper() {
        return this.denturesUpper;
    }

    public void setDenturesUpper(Boolean denturesUpper) {
        this.denturesUpper = denturesUpper;
    }

    @Column(name = "`DiathermyAppliedBy`", nullable = true, length = 255)
    public String getDiathermyAppliedBy() {
        return this.diathermyAppliedBy;
    }

    public void setDiathermyAppliedBy(String diathermyAppliedBy) {
        this.diathermyAppliedBy = diathermyAppliedBy;
    }

    @Column(name = "`DiathermyRemovedBy`", nullable = true, length = 255)
    public String getDiathermyRemovedBy() {
        return this.diathermyRemovedBy;
    }

    public void setDiathermyRemovedBy(String diathermyRemovedBy) {
        this.diathermyRemovedBy = diathermyRemovedBy;
    }

    @Column(name = "`DrugAdded`", nullable = true)
    public Boolean getDrugAdded() {
        return this.drugAdded;
    }

    public void setDrugAdded(Boolean drugAdded) {
        this.drugAdded = drugAdded;
    }

    @Column(name = "`Duovisc`", nullable = true)
    public Boolean getDuovisc() {
        return this.duovisc;
    }

    public void setDuovisc(Boolean duovisc) {
        this.duovisc = duovisc;
    }

    @Column(name = "`ECG`", nullable = true)
    public Boolean getEcg() {
        return this.ecg;
    }

    public void setEcg(Boolean ecg) {
        this.ecg = ecg;
    }

    @Column(name = "`ElbowGels`", nullable = true)
    public Boolean getElbowGels() {
        return this.elbowGels;
    }

    public void setElbowGels(Boolean elbowGels) {
        this.elbowGels = elbowGels;
    }

    @Column(name = "`Emboard`", nullable = true)
    public Boolean getEmboard() {
        return this.emboard;
    }

    public void setEmboard(Boolean emboard) {
        this.emboard = emboard;
    }

    @Column(name = "`FluidWarmer`", nullable = true)
    public Boolean getFluidWarmer() {
        return this.fluidWarmer;
    }

    public void setFluidWarmer(Boolean fluidWarmer) {
        this.fluidWarmer = fluidWarmer;
    }

    @Column(name = "`HeadRing`", nullable = true)
    public Boolean getHeadRing() {
        return this.headRing;
    }

    public void setHeadRing(Boolean headRing) {
        this.headRing = headRing;
    }

    @Column(name = "`HeelGels`", nullable = true)
    public Boolean getHeelGels() {
        return this.heelGels;
    }

    public void setHeelGels(Boolean heelGels) {
        this.heelGels = heelGels;
    }

    @Column(name = "`HydrogenPeroxide3`", nullable = true)
    public Boolean getHydrogenPeroxide3() {
        return this.hydrogenPeroxide3;
    }

    public void setHydrogenPeroxide3(Boolean hydrogenPeroxide3) {
        this.hydrogenPeroxide3 = hydrogenPeroxide3;
    }

    @Column(name = "`HydrogenPeroxide6`", nullable = true)
    public Boolean getHydrogenPeroxide6() {
        return this.hydrogenPeroxide6;
    }

    public void setHydrogenPeroxide6(Boolean hydrogenPeroxide6) {
        this.hydrogenPeroxide6 = hydrogenPeroxide6;
    }

    @Column(name = "`InfiltrationOther`", nullable = true)
    public Boolean getInfiltrationOther() {
        return this.infiltrationOther;
    }

    public void setInfiltrationOther(Boolean infiltrationOther) {
        this.infiltrationOther = infiltrationOther;
    }

    @Column(name = "`InfiltrationOtherDesc`", nullable = true, length = 255)
    public String getInfiltrationOtherDesc() {
        return this.infiltrationOtherDesc;
    }

    public void setInfiltrationOtherDesc(String infiltrationOtherDesc) {
        this.infiltrationOtherDesc = infiltrationOtherDesc;
    }

    @Column(name = "`InfiltrationOxymetazaline`", nullable = true)
    public Boolean getInfiltrationOxymetazaline() {
        return this.infiltrationOxymetazaline;
    }

    public void setInfiltrationOxymetazaline(Boolean infiltrationOxymetazaline) {
        this.infiltrationOxymetazaline = infiltrationOxymetazaline;
    }

    @Column(name = "`Intact`", nullable = true)
    public Boolean getIntact() {
        return this.intact;
    }

    public void setIntact(Boolean intact) {
        this.intact = intact;
    }

    @Column(name = "`IrrigationSolutionOther`", nullable = true)
    public Boolean getIrrigationSolutionOther() {
        return this.irrigationSolutionOther;
    }

    public void setIrrigationSolutionOther(Boolean irrigationSolutionOther) {
        this.irrigationSolutionOther = irrigationSolutionOther;
    }

    @Column(name = "`IrrigationSolutionOtherDesc`", nullable = true, length = 255)
    public String getIrrigationSolutionOtherDesc() {
        return this.irrigationSolutionOtherDesc;
    }

    public void setIrrigationSolutionOtherDesc(String irrigationSolutionOtherDesc) {
        this.irrigationSolutionOtherDesc = irrigationSolutionOtherDesc;
    }

    @Column(name = "`JBoards`", nullable = true)
    public Boolean getJboards() {
        return this.jboards;
    }

    public void setJboards(Boolean jboards) {
        this.jboards = jboards;
    }

    @Column(name = "`Kenacomb`", nullable = true)
    public Boolean getKenacomb() {
        return this.kenacomb;
    }

    public void setKenacomb(Boolean kenacomb) {
        this.kenacomb = kenacomb;
    }

    @Column(name = "`LateralLeft`", nullable = true)
    public Boolean getLateralLeft() {
        return this.lateralLeft;
    }

    public void setLateralLeft(Boolean lateralLeft) {
        this.lateralLeft = lateralLeft;
    }

    @Column(name = "`LateralRight`", nullable = true)
    public Boolean getLateralRight() {
        return this.lateralRight;
    }

    public void setLateralRight(Boolean lateralRight) {
        this.lateralRight = lateralRight;
    }

    @Column(name = "`Lignocaine1`", nullable = true)
    public Boolean getLignocaine1() {
        return this.lignocaine1;
    }

    public void setLignocaine1(Boolean lignocaine1) {
        this.lignocaine1 = lignocaine1;
    }

    @Column(name = "`LithotomiPoles`", nullable = true)
    public Boolean getLithotomiPoles() {
        return this.lithotomiPoles;
    }

    public void setLithotomiPoles(Boolean lithotomiPoles) {
        this.lithotomiPoles = lithotomiPoles;
    }

    @Column(name = "`LithotomiStirrups`", nullable = true)
    public Boolean getLithotomiStirrups() {
        return this.lithotomiStirrups;
    }

    public void setLithotomiStirrups(Boolean lithotomiStirrups) {
        this.lithotomiStirrups = lithotomiStirrups;
    }

    @Column(name = "`MarcainAdrenaline`", nullable = true)
    public Boolean getMarcainAdrenaline() {
        return this.marcainAdrenaline;
    }

    public void setMarcainAdrenaline(Boolean marcainAdrenaline) {
        this.marcainAdrenaline = marcainAdrenaline;
    }

    @Column(name = "`MedicationAdrenaline`", nullable = true)
    public Boolean getMedicationAdrenaline() {
        return this.medicationAdrenaline;
    }

    public void setMedicationAdrenaline(Boolean medicationAdrenaline) {
        this.medicationAdrenaline = medicationAdrenaline;
    }

    @Column(name = "`MedicationsOxymetazaline`", nullable = true)
    public Boolean getMedicationsOxymetazaline() {
        return this.medicationsOxymetazaline;
    }

    public void setMedicationsOxymetazaline(Boolean medicationsOxymetazaline) {
        this.medicationsOxymetazaline = medicationsOxymetazaline;
    }

    @Column(name = "`monitoringInAntNone`", nullable = true)
    public Boolean getMonitoringInAntNone() {
        return this.monitoringInAntNone;
    }

    public void setMonitoringInAntNone(Boolean monitoringInAntNone) {
        this.monitoringInAntNone = monitoringInAntNone;
    }

    @Column(name = "`Monopolar`", nullable = true)
    public Boolean getMonopolar() {
        return this.monopolar;
    }

    public void setMonopolar(Boolean monopolar) {
        this.monopolar = monopolar;
    }

    @Column(name = "`Naropin1`", nullable = true)
    public Boolean getNaropin1() {
        return this.naropin1;
    }

    public void setNaropin1(Boolean naropin1) {
        this.naropin1 = naropin1;
    }

    @Column(name = "`Naropin75`", nullable = true)
    public Boolean getNaropin75() {
        return this.naropin75;
    }

    public void setNaropin75(Boolean naropin75) {
        this.naropin75 = naropin75;
    }

    @Column(name = "`NormalSalineIrrigation`", nullable = true)
    public Boolean getNormalSalineIrrigation() {
        return this.normalSalineIrrigation;
    }

    public void setNormalSalineIrrigation(Boolean normalSalineIrrigation) {
        this.normalSalineIrrigation = normalSalineIrrigation;
    }

    @Column(name = "`NormalSalineIV`", nullable = true)
    public Boolean getNormalSalineIv() {
        return this.normalSalineIv;
    }

    public void setNormalSalineIv(Boolean normalSalineIv) {
        this.normalSalineIv = normalSalineIv;
    }

    @Column(name = "`Platesite`", nullable = true)
    public Boolean getPlatesite() {
        return this.platesite;
    }

    public void setPlatesite(Boolean platesite) {
        this.platesite = platesite;
    }

    @Column(name = "`plusOximetry`", nullable = true)
    public Boolean getPlusOximetry() {
        return this.plusOximetry;
    }

    public void setPlusOximetry(Boolean plusOximetry) {
        this.plusOximetry = plusOximetry;
    }

    @Column(name = "`PositioningAidsOther`", nullable = true)
    public Boolean getPositioningAidsOther() {
        return this.positioningAidsOther;
    }

    public void setPositioningAidsOther(Boolean positioningAidsOther) {
        this.positioningAidsOther = positioningAidsOther;
    }

    @Column(name = "`PrepSolutionOther`", nullable = true)
    public Boolean getPrepSolutionOther() {
        return this.prepSolutionOther;
    }

    public void setPrepSolutionOther(Boolean prepSolutionOther) {
        this.prepSolutionOther = prepSolutionOther;
    }

    @Column(name = "`Prone`", nullable = true)
    public Boolean getProne() {
        return this.prone;
    }

    public void setProne(Boolean prone) {
        this.prone = prone;
    }

    @Column(name = "`ProvidoeIodine10`", nullable = true)
    public Boolean getProvidoeIodine10() {
        return this.providoeIodine10;
    }

    public void setProvidoeIodine10(Boolean providoeIodine10) {
        this.providoeIodine10 = providoeIodine10;
    }

    @Column(name = "`ProvidoeIodine5`", nullable = true)
    public Boolean getProvidoeIodine5() {
        return this.providoeIodine5;
    }

    public void setProvidoeIodine5(Boolean providoeIodine5) {
        this.providoeIodine5 = providoeIodine5;
    }

    @Column(name = "`ProvidoneIodine`", nullable = true)
    public Boolean getProvidoneIodine() {
        return this.providoneIodine;
    }

    public void setProvidoneIodine(Boolean providoneIodine) {
        this.providoneIodine = providoneIodine;
    }

    @Column(name = "`Provisc`", nullable = true)
    public Boolean getProvisc() {
        return this.provisc;
    }

    public void setProvisc(Boolean provisc) {
        this.provisc = provisc;
    }

    @Column(name = "`ptPositionOther`", nullable = true)
    public Boolean getPtPositionOther() {
        return this.ptPositionOther;
    }

    public void setPtPositionOther(Boolean ptPositionOther) {
        this.ptPositionOther = ptPositionOther;
    }

    @Column(name = "`signinForTimeoutComplete`", nullable = true)
    public Boolean getSigninForTimeoutComplete() {
        return this.signinForTimeoutComplete;
    }

    public void setSigninForTimeoutComplete(Boolean signinForTimeoutComplete) {
        this.signinForTimeoutComplete = signinForTimeoutComplete;
    }

    @Column(name = "`SitesUsed`", nullable = true, length = 255)
    public String getSitesUsed() {
        return this.sitesUsed;
    }

    public void setSitesUsed(String sitesUsed) {
        this.sitesUsed = sitesUsed;
    }

    @Column(name = "`SkinIntegrityOther`", nullable = true)
    public Boolean getSkinIntegrityOther() {
        return this.skinIntegrityOther;
    }

    public void setSkinIntegrityOther(Boolean skinIntegrityOther) {
        this.skinIntegrityOther = skinIntegrityOther;
    }

    @Column(name = "`SkinIntegrityOtherDesc`", nullable = true, length = 2147483647)
    public String getSkinIntegrityOtherDesc() {
        return this.skinIntegrityOtherDesc;
    }

    public void setSkinIntegrityOtherDesc(String skinIntegrityOtherDesc) {
        this.skinIntegrityOtherDesc = skinIntegrityOtherDesc;
    }

    @Column(name = "`SkinPrepOther`", nullable = true)
    public Boolean getSkinPrepOther() {
        return this.skinPrepOther;
    }

    public void setSkinPrepOther(Boolean skinPrepOther) {
        this.skinPrepOther = skinPrepOther;
    }

    @Column(name = "`SkinPrepOtherDisc`", nullable = true, length = 255)
    public String getSkinPrepOtherDisc() {
        return this.skinPrepOtherDisc;
    }

    public void setSkinPrepOtherDisc(String skinPrepOtherDisc) {
        this.skinPrepOtherDisc = skinPrepOtherDisc;
    }

    @Column(name = "`SodiumBicarbonate`", nullable = true)
    public Boolean getSodiumBicarbonate() {
        return this.sodiumBicarbonate;
    }

    public void setSodiumBicarbonate(Boolean sodiumBicarbonate) {
        this.sodiumBicarbonate = sodiumBicarbonate;
    }

    @Column(name = "`StockingKnee`", nullable = true)
    public Boolean getStockingKnee() {
        return this.stockingKnee;
    }

    public void setStockingKnee(Boolean stockingKnee) {
        this.stockingKnee = stockingKnee;
    }

    @Column(name = "`StockingLeft`", nullable = true)
    public Boolean getStockingLeft() {
        return this.stockingLeft;
    }

    public void setStockingLeft(Boolean stockingLeft) {
        this.stockingLeft = stockingLeft;
    }

    @Column(name = "`StockingRight`", nullable = true)
    public Boolean getStockingRight() {
        return this.stockingRight;
    }

    public void setStockingRight(Boolean stockingRight) {
        this.stockingRight = stockingRight;
    }

    @Column(name = "`StockingThigh`", nullable = true)
    public Boolean getStockingThigh() {
        return this.stockingThigh;
    }

    public void setStockingThigh(Boolean stockingThigh) {
        this.stockingThigh = stockingThigh;
    }

    @Column(name = "`Supine`", nullable = true)
    public Boolean getSupine() {
        return this.supine;
    }

    public void setSupine(Boolean supine) {
        this.supine = supine;
    }

    @Column(name = "`Temperature`", nullable = true)
    public Boolean getTemperature() {
        return this.temperature;
    }

    public void setTemperature(Boolean temperature) {
        this.temperature = temperature;
    }

    @Column(name = "`Tisseel`", nullable = true)
    public Boolean getTisseel() {
        return this.tisseel;
    }

    public void setTisseel(Boolean tisseel) {
        this.tisseel = tisseel;
    }

    @Column(name = "`TotalEnvelops`", nullable = true, length = 255)
    public String getTotalEnvelops() {
        return this.totalEnvelops;
    }

    public void setTotalEnvelops(String totalEnvelops) {
        this.totalEnvelops = totalEnvelops;
    }

    @Column(name = "`Trenderlengberg`", nullable = true)
    public Boolean getTrenderlengberg() {
        return this.trenderlengberg;
    }

    public void setTrenderlengberg(Boolean trenderlengberg) {
        this.trenderlengberg = trenderlengberg;
    }

    @Column(name = "`VelcroStrap`", nullable = true)
    public Boolean getVelcroStrap() {
        return this.velcroStrap;
    }

    public void setVelcroStrap(Boolean velcroStrap) {
        this.velcroStrap = velcroStrap;
    }

    @Column(name = "`WarmBlanket`", nullable = true)
    public Boolean getWarmBlanket() {
        return this.warmBlanket;
    }

    public void setWarmBlanket(Boolean warmBlanket) {
        this.warmBlanket = warmBlanket;
    }

    @Column(name = "`WarmingNone`", nullable = true)
    public Boolean getWarmingNone() {
        return this.warmingNone;
    }

    public void setWarmingNone(Boolean warmingNone) {
        this.warmingNone = warmingNone;
    }

    @Column(name = "`WaterforIrrigation`", nullable = true)
    public Boolean getWaterforIrrigation() {
        return this.waterforIrrigation;
    }

    public void setWaterforIrrigation(Boolean waterforIrrigation) {
        this.waterforIrrigation = waterforIrrigation;
    }

    @Column(name = "`Wedge`", nullable = true)
    public Boolean getWedge() {
        return this.wedge;
    }

    public void setWedge(Boolean wedge) {
        this.wedge = wedge;
    }

    @Column(name = "`XrayPresent`", nullable = true)
    public Boolean getXrayPresent() {
        return this.xrayPresent;
    }

    public void setXrayPresent(Boolean xrayPresent) {
        this.xrayPresent = xrayPresent;
    }

    @Column(name = "`Xylocaine2`", nullable = true)
    public Boolean getXylocaine2() {
        return this.xylocaine2;
    }

    public void setXylocaine2(Boolean xylocaine2) {
        this.xylocaine2 = xylocaine2;
    }

    @Column(name = "`XylocaineAdrenaline1`", nullable = true)
    public Boolean getXylocaineAdrenaline1() {
        return this.xylocaineAdrenaline1;
    }

    public void setXylocaineAdrenaline1(Boolean xylocaineAdrenaline1) {
        this.xylocaineAdrenaline1 = xylocaineAdrenaline1;
    }

    @Column(name = "`XylocaineAdrenaline2`", nullable = true)
    public Boolean getXylocaineAdrenaline2() {
        return this.xylocaineAdrenaline2;
    }

    public void setXylocaineAdrenaline2(Boolean xylocaineAdrenaline2) {
        this.xylocaineAdrenaline2 = xylocaineAdrenaline2;
    }

    @Column(name = "`Marcain5`", nullable = true)
    public Boolean getMarcain5() {
        return this.marcain5;
    }

    public void setMarcain5(Boolean marcain5) {
        this.marcain5 = marcain5;
    }

    @Column(name = "`SkinIntergrityImageText`", nullable = true, length = 2147483647)
    public String getSkinIntergrityImageText() {
        return this.skinIntergrityImageText;
    }

    public void setSkinIntergrityImageText(String skinIntergrityImageText) {
        this.skinIntergrityImageText = skinIntergrityImageText;
    }

    @Column(name = "`createdBy`", nullable = true, length = 255)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "`createdDate`", nullable = false)
    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "`lastUpdateBy`", nullable = true, length = 255)
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }

    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    @Column(name = "`lastUpdateDate`", nullable = false)
    public Timestamp getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Timestamp lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`obsptid`", referencedColumnName = "`obsptid`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK583D6F6F389B2119`"))
    @Fetch(FetchMode.JOIN)
    public Obspatients getObspatients() {
        return this.obspatients;
    }

    public void setObspatients(Obspatients obspatients) {
        if(obspatients != null) {
            this.obsptid = obspatients.getObsptid();
        }

        this.obspatients = obspatients;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Surgchecklist)) return false;
        final Surgchecklist surgchecklist = (Surgchecklist) o;
        return Objects.equals(getChecklistId(), surgchecklist.getChecklistId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getChecklistId());
    }
}