/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JsontextTemp generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`JSONTextTemp`")
public class JsontextTemp implements Serializable {

    private Integer id;
    private String jsonText;
    private String personalData;
    private String fundDetails;
    private String nextOfkin;
    private String medicalHistory;
    private String patientNo;
    private Boolean isFormComplete;
    private String refData;
    private String email;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`JsonText`", nullable = true, length = 2147483647)
    public String getJsonText() {
        return this.jsonText;
    }

    public void setJsonText(String jsonText) {
        this.jsonText = jsonText;
    }

    @Column(name = "`personalData`", nullable = true, length = 2147483647)
    public String getPersonalData() {
        return this.personalData;
    }

    public void setPersonalData(String personalData) {
        this.personalData = personalData;
    }

    @Column(name = "`fundDetails`", nullable = true, length = 2147483647)
    public String getFundDetails() {
        return this.fundDetails;
    }

    public void setFundDetails(String fundDetails) {
        this.fundDetails = fundDetails;
    }

    @Column(name = "`nextOfkin`", nullable = true, length = 2147483647)
    public String getNextOfkin() {
        return this.nextOfkin;
    }

    public void setNextOfkin(String nextOfkin) {
        this.nextOfkin = nextOfkin;
    }

    @Column(name = "`medicalHistory`", nullable = true, length = 2147483647)
    public String getMedicalHistory() {
        return this.medicalHistory;
    }

    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }

    @Column(name = "`patient_no`", nullable = true, length = 255)
    public String getPatientNo() {
        return this.patientNo;
    }

    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo;
    }

    @Column(name = "`isFormComplete`", nullable = true)
    public Boolean getIsFormComplete() {
        return this.isFormComplete;
    }

    public void setIsFormComplete(Boolean isFormComplete) {
        this.isFormComplete = isFormComplete;
    }

    @Column(name = "`refData`", nullable = true, length = 2147483647)
    public String getRefData() {
        return this.refData;
    }

    public void setRefData(String refData) {
        this.refData = refData;
    }

    @Column(name = "`email`", nullable = true, length = 255)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof JsontextTemp)) return false;
        final JsontextTemp jsontextTemp = (JsontextTemp) o;
        return Objects.equals(getId(), jsontextTemp.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}