/*Copyright (c) 2015-2016 medicalwizard.com.au All Rights Reserved.
 This software is the confidential and proprietary information of medicalwizard.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with medicalwizard.com.au*/
package com.restwiz.cwmwsql;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pteducation generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`pteducation`")
public class Pteducation implements Serializable {

    private Integer idno;
    private String patientNo;
    private String eduidno;
    private Boolean readinpp;
    private String comment;
    private LocalDateTime viewat;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`idno`", nullable = false, scale = 0, precision = 10)
    public Integer getIdno() {
        return this.idno;
    }

    public void setIdno(Integer idno) {
        this.idno = idno;
    }

    @Column(name = "`patient_no`", nullable = true, length = 14)
    public String getPatientNo() {
        return this.patientNo;
    }

    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo;
    }

    @Column(name = "`eduidno`", nullable = true, length = 255)
    public String getEduidno() {
        return this.eduidno;
    }

    public void setEduidno(String eduidno) {
        this.eduidno = eduidno;
    }

    @Column(name = "`readinpp`", nullable = true)
    public Boolean getReadinpp() {
        return this.readinpp;
    }

    public void setReadinpp(Boolean readinpp) {
        this.readinpp = readinpp;
    }

    @Column(name = "`comment`", nullable = true, length = 2147483647)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "`viewat`", nullable = true)
    public LocalDateTime getViewat() {
        return this.viewat;
    }

    public void setViewat(LocalDateTime viewat) {
        this.viewat = viewat;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Pteducation)) return false;
        final Pteducation pteducation = (Pteducation) o;
        return Objects.equals(getIdno(), pteducation.getIdno());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdno());
    }
}